version: '3.8'

services:
  # 1. Contenedor de Laravel (PHP)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sinki_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - sinki_network

  # 2. Contenedor de Nginx (Proxy)
  web:
    image: nginx:alpine
    container_name: sinki_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sinki_network
    depends_on:
      - app

  # 3. Contenedor de Base de Datos (MySQL)
  db:
    image: mysql:8.0
    container_name: sinki_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sinki_network

networks:
  sinki_network:
    driver: bridge

volumes:
  db_data: